[tox]
min_version = 4.0
requires =
    tox-pypi-filter>=0.14
envlist =
    py{312,313,314}
    py314-devdeps
    py312-oldestdeps
    build_docs
    codestyle
    linkcheck
isolated_build = true


[testenv]
# The following option combined with the use of the tox-pypi-filter above allows
# project-wide pinning of dependencies, e.g. if new versions of pytest do not
# work correctly with pytest-astropy plugins. Most of the time the pinnings file
# should be empty.
#pypi_filter_requirements = https://raw.githubusercontent.com/sunpy/package-template/master/sunpy_version_pins.txt

# Run the tests in a temporary directory to make sure that we don't import
# the package from the source tree
changedir = .tmp/{envname}
# Pass through the following environment variables which may be needed for the CI
passenv = HOME, WINDIR, LC_ALL, LC_CTYPE, CC, CI, TRAVIS


description =
    run tests
    devdeps: with the latest developer version of key dependencies
    oldestdeps: with the oldest supported version of key dependencies

setenv =
    devdeps: PIP_EXTRA_INDEX_URL = https://pypi.anaconda.org/astropy/simple https://pypi.anaconda.org/scientific-python-nightly-wheels/simple https://pypi.anaconda.org/liberfa/simple
    MPLBACKEND = agg
deps =
    # Avoid adding this to the pyproject.toml as a dependency
    pytest-xdist
    # devdeps is intended to be used to install the latest developer version of key dependencies.
    # For packages which publish nightly wheels this will pull the latest nightly
    devdeps: astropy>=0.0.dev0
    devdeps: matplotlib>=0.0.dev0
    devdeps: numpy>=0.0.dev0
    devdeps: pytest>=0.0.dev0
    devdeps: reproject>=0.0.dev0
    # Packages without nightly wheels will be built from source like this
    devdeps: git+https://github.com/sunpy/sunpy
    devdeps: git+https://github.com/TCDSolar/xrayvision
    devdeps: git+https://github.com/chaimleib/intervaltree
    devdeps: git+https://github.com/ehsteve/roentgen
    # Handle minimum dependencies via minimum_dependencies
    oldestdeps: minimum_dependencies
extras =
    tests
commands_pre =
    oldestdeps: minimum_dependencies stixpy --extras  --filename requirements-min.txt
    oldestdeps: pip install -r requirements-min.txt
    oldestdeps: python -c "import astropy.time; astropy.time.update_leap_seconds()"
    pip freeze --all --no-input
commands =
    pytest \
    -vvv \
    --remote-data=any \
    --pyargs stixpy \
    --cov stixpy \
    --cov-config={toxinidir}/.coveragerc \
    {toxinidir}/docs \
    {posargs}

[testenv:build_docs]
changedir = docs
description = invoke sphinx-build to build the HTML docs
extras = docs
commands =
    pip freeze --all --no-input
    sphinx-build \
    -j auto \
    --color \
    -W \
    --keep-going \
    -b html \
    -d _build/.doctrees \
    . \
    _build/html \
    {posargs}
    python -c 'import pathlib; print("Documentation available under file://\{0\}".format(pathlib.Path(r"{toxinidir}") / "docs" / "_build" / "index.html"))'

[testenv:linkcheck]
changedir = docs
description = Invoke sphinx-build to check the URLS within the docs
extras =
    docs
commands =
    pip freeze --all --no-input
    sphinx-build \
    -qqq \
    --color \
    -b linkcheck \
    -D plot_gallery=0 \
    . \
    _build/html \
    {posargs}

[testenv:codestyle]
pypi_filter =
skip_install = true
description = Run all style and file checks with pre-commit
deps =
    pre-commit
commands =
    pre-commit install-hooks
    pre-commit run --color always --all-files --show-diff-on-failure
